api:
  version: "1.0"
  port: 8000
  host: "0.0.0.0"
  debug: false
  rate_limit:
    max_requests: 100
    timeframe: 60  # seconds

ai:
  models:
    primary: "claude-3-opus-20240229"
    fallback: "mixtral-8x7b-32768"
  parameters:
    temperature: 0.7
    max_tokens: 1000
    context_window: 5
    cache_responses: true

blockchain:
  networks:
    solana:
      rpc_url: "${SOLANA_RPC_URL}"
      ws_url: "${SOLANA_WS_URL}"
      commitment: "confirmed"
    ethereum:
      rpc_url: "${ETH_RPC_URL}"
      chain_id: 1

social:
  twitter:
    api_version: 2
    tweet_limit: 10
    monitor_mentions: true
  discord:
    command_prefix: "!"
    guild_id: "${DISCORD_GUILD_ID}"

logging:
  level: "INFO"
  file: "logs/agent.log"
  max_size: 10485760  # 10MB
  backup_count: 5

security:
  api_keys:
    valid_duration: 3600
    max_active: 10
  rate_limiting: true
  ip_whitelist: []
