api:
  version: "1.0"
  port: 8000
  host: "0.0.0.0"
  debug: false
  rate_limit:
    max_requests: 100
    timeframe: 60  # seconds

ai:
  primary_model: "claude-3-opus"
  backup_model: "groq"
  temperature: 0.7
  max_tokens: 1000
  context_window: 5
  cache_responses: true

blockchain:
  networks:
    - name: "solana"
      rpc_url: "https://api.mainnet-beta.solana.com"
      ws_url: "wss://api.mainnet-beta.solana.com"
    - name: "ethereum"
      rpc_url: "https://eth-mainnet.g.alchemy.com/v2/your-api-key"
  
  wallets:
    primary:
      type: "crossmint"
      auto_fund: false
      max_transaction: 1000
    backup:
      type: "local"
      auto_fund: false

social:
  twitter:
    api_version: 2
    tweet_limit: 10
    monitor_mentions: true
  discord:
    command_prefix: "!"
    guild_id: "your-guild-id"

logging:
  level: "INFO"
  file: "agent.log"
  max_size: 10485760  # 10MB
  backup_count: 5

security:
  api_keys:
    valid_duration: 3600  # seconds
    max_active: 10
  rate_limiting: true
  ip_whitelist: []