agent:
  name: "OmniAGI"
  version: "1.0.0"
  mode: "production"  # development, production

ai:
  claude:
    model: "claude-3-opus-20240229"
    max_tokens: 2000
  groq:
    model: "mixtral-8x7b-32768"
    temperature: 0.7

blockchain:
  solana:
    rpc_url: "${SOLANA_RPC_URL}"
    commitment: "confirmed"
    max_retries: 3
  ethereum:
    rpc_url: "${ETH_RPC_URL}"
    chain_id: 1
    gas_limit: 500000

investment:
  portfolio:
    max_position_size: 0.2
    min_position_size: 0.01
    rebalance_threshold: 0.05
  risk:
    max_drawdown: 0.15
    var_confidence: 0.95
    correlation_threshold: 0.7

communication:
  discord:
    channels:
      announcements: "${DISCORD_ANNOUNCE_CHANNEL}"
      trading: "${DISCORD_TRADING_CHANNEL}"
      community: "${DISCORD_COMMUNITY_CHANNEL}"
  twitter:
    post_interval: 3600
    max_daily_posts: 24
